import Link from 'next/link'
import { ArrowLeft, Heart } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service — PawCheck',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="container py-6 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2">
          <div className="w-9 h-9 rounded-xl bg-forest-600 flex items-center justify-center">
            <Heart className="w-5 h-5 text-amber-400 fill-amber-400" />
          </div>
          <span className="font-display text-xl font-bold text-ink">PawCheck</span>
        </Link>
        <Link href="/" className="text-sm text-ink-mute hover:text-ink inline-flex items-center gap-1">
          <ArrowLeft className="w-4 h-4" />
          Home
        </Link>
      </header>

      <main className="container max-w-3xl py-8 lg:py-16">
        <h1 className="font-display text-4xl md:text-5xl font-bold text-ink mb-4">
          Terms of Service
        </h1>
        <p className="text-ink-mute mb-12">Last updated: May 19, 2026</p>

        <div className="space-y-6 text-ink-soft leading-relaxed">
          <p className="p-4 bg-urgency-red/5 border border-urgency-red/20 rounded-xl text-sm">
            <strong className="text-ink">CRITICAL: This is a starting template only.</strong>{' '}
            You MUST have a qualified attorney review and customize this
            document before launch. Pet health software carries unique legal
            risks (unauthorized practice of veterinary medicine claims, FDA
            regulation considerations, class action exposure). Do not launch
            without proper legal review. Budget $1,500-2,500 for proper TOS,
            Privacy, and Medical Disclaimer drafting.
          </p>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              1. Acceptance of Terms
            </h2>
            <p>
              By creating an account or using PawCheck, you agree to these
              Terms of Service. If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              2. NOT VETERINARY MEDICAL ADVICE
            </h2>
            <p className="font-medium text-ink">
              PawCheck is an informational service. It does NOT provide
              veterinary medical advice, diagnosis, or treatment. The
              information generated by our AI is for educational and
              informational purposes only.
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>PawCheck is not a substitute for professional veterinary care</li>
              <li>Always consult a licensed veterinarian for medical advice</li>
              <li>In emergencies, contact an emergency veterinary hospital immediately</li>
              <li>We do not establish a veterinarian-client-patient relationship</li>
              <li>You assume all risk for actions taken based on PawCheck information</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              3. Eligibility
            </h2>
            <p>
              You must be at least 18 years old and have the legal capacity to
              enter into binding contracts to use PawCheck.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              4. Account Responsibilities
            </h2>
            <p>You are responsible for:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Providing accurate information about your pet</li>
              <li>Notifying us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              5. Subscriptions and Payments
            </h2>
            <p>
              Premium subscriptions are billed monthly or annually as selected.
              Subscriptions auto-renew until canceled. You may cancel at any
              time through your account settings. Refunds are provided at our
              discretion and generally only for technical errors.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              6. Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the service for any illegal purpose</li>
              <li>Upload content that violates third-party rights</li>
              <li>Attempt to reverse engineer or copy the service</li>
              <li>Use the service for animals other than your own pets</li>
              <li>Resell, white-label, or commercialize our AI outputs</li>
              <li>Use the service to provide veterinary services to others</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              7. Intellectual Property
            </h2>
            <p>
              The PawCheck service, including software, design, branding, and
              AI prompts, is our intellectual property. You retain ownership of
              photos you upload, but grant us a license to use them to provide
              the service.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              8. Disclaimer of Warranties
            </h2>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT
              WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT
              NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT
              AI ASSESSMENTS ARE ACCURATE, COMPLETE, OR RELIABLE.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              9. Limitation of Liability
            </h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, PAWCHECK SHALL NOT BE
              LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
              PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION HARM TO YOUR PET,
              VETERINARY COSTS, OR LOSS OF AFFECTION. OUR TOTAL LIABILITY SHALL
              NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE
              CLAIM.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              10. Indemnification
            </h2>
            <p>
              You agree to indemnify and hold PawCheck harmless from any
              claims, damages, or expenses arising from your use of the
              service, your violation of these Terms, or your violation of any
              third-party rights.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              11. Termination
            </h2>
            <p>
              We may suspend or terminate your account at any time for
              violations of these Terms. You may cancel your account at any
              time through your settings.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              12. Governing Law
            </h2>
            <p>
              These Terms are governed by the laws of [YOUR JURISDICTION].
              Disputes shall be resolved through binding arbitration in
              [YOUR JURISDICTION].
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              13. Changes
            </h2>
            <p>
              We may update these Terms at any time. Continued use of the
              service after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="font-display text-2xl font-semibold text-ink mt-8 mb-3">
              14. Contact
            </h2>
            <p>Questions? Email legal@pawcheck.app.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
